### ISSUE TITLE
OPTIONS method causes a crash

### ISSUE THREAD

**Issue by pwaller** [wichitacode/flask-compress#12]
If you do a http options request to a URL wrapped with this middleware, it crashes:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1691, in process_response
    response = handler(response)
  File "/usr/local/lib/python3.4/dist-packages/flask_compress.py", line 79, in after_request
    response.content_length < app.config['COMPRESS_MIN_SIZE'] or
TypeError: unorderable types: NoneType() < int()
```

I guess the fix is to change the condition to:

```python
(response.content_length and response.content_length < app.config['COMPRESS_MIN_SIZE']) or
```

**Comment by libwilliam** [comment]
I'm wondering how it got into that scenario. All of the COMPRESS_* values should be initialized in init_app. A few lines above it it is checking for COMPRESS_MIMETYPES and it doesn't crash. Is there anything unique about your scenario?

**Comment by pwaller** [comment]
My understanding was that it is `response.content_length` which is None (OPTIONS has no body), but now I realise that I didn't actually check.

**Comment by libwilliam** [comment]
I bet you are right, that makes more sense to me. I'll look into it and get back to your shortly.

**Comment by libwilliam** [comment]
Can you write a small snippet in `test_flask_compress.py` that reproduces this for me? So far I keep getting a response.content_length of 0 when doing an `options` request.

```python
client = self.app.test_client()                                                                                                                                                                                                  
response = client.options('/small/', headers=[('Accept-Encoding', 'gzip')])                                                                                                                                                                
self.assertEqual(response.status_code, 200)                                                                                                                                                                                      
print(response.content_length)  
```

Thank you

**Comment by pwaller** [comment]
I currently cannot reproduce it locally, only in production. Maybe it is a bug that got fixed already somewhere? I will reopen if/when I can reproduce this in a controlled environment.

**Comment by pwaller** [comment]
Right, I can reproduce it in development now. The problem was that I wasn't passing `--compressed` to curl, and it was working against the live site since there was a proxy infront of the daemon which supported compression.

I'm suspecting a flask bug right now, since the `HEAD` method is actually hanging.

**Comment by pwaller** [comment]
I added this test to your code, and it reproduces the problem when running `nose`.

```

    def test_content_length_options(self):
        client = self.app.test_client()
        headers = [('Accept-Encoding', 'gzip')]
        response = client.options('/small/', headers=headers)
        self.assertEqual(response.status_code, 200)
        print(response.content_length)
```
