### ISSUE TITLE
Document that it's not active in debug mode

### ISSUE THREAD

**Issue by wassname** [wichitacode/flask-compress#14]
I was pulling my hair out trying to get this working until I saw "if app.debug " in the source code and switched off debugging. I think this should be added to the README.md,

**Comment by libwilliam** [comment]
I agree. I will amend the documentation tomorrow. Thank you for letting me know!

**Comment by wassname** [comment]
no problems, thanks for making this!

**Comment by libwilliam** [comment]
I re-added the debug documentation that got stripped out a few commits back. I should have caught this during review.

It probably makes more sense to have the documentation purely in README.md at this point. I will look into porting over.

**Comment by pwaller** [comment]
Is there a good reason to turn it off during debug? I observe that this confused me, and separately another dev on my team too.

**Comment by pwaller** [comment]
(and docs probably wouldn't have helped the existence of the confusion much)

**Comment by libwilliam** [comment]
The original idea was that during development you weren't forced to look at the compressed javascript, css, etc. With browsers automatically formatting those files even if they are compressed, this probably isn't a concern. Since both of you got tripped up by it, it is probably a good idea to remove it. If someone wants to temporarily disable the compression all they have to do it comment out one line in their app. What do you think?

**Comment by pwaller** [comment]
Yes, that would be good.

I don't understand though, why would a developer ever find themselves looking at compressed javascript? All of the tools I use (curl, browsers, etc) show the resources after decompression..

**Comment by libwilliam** [comment]
It was purely out of flexibility. I agree is a dated belief with modern browsers. I will pull that code out while I'm porting to README.md.

**Comment by libwilliam** [comment]
I went ahead and made the change. If you are using trunk you will no longer need to have `app.debug = false`. I'll put out an official release once I port over the documentation.

**Comment by libwilliam** [comment]
I removed the `app.debug = false` requirement, updated the Sphinx documentation and moved most of it into README.md for easier viewing in Github. Are there any other improvements you all would like to see before I spin a new release?

**Comment by pwaller** [comment]
None that spring to mind for me.

**Comment by pwaller** [comment]
Thanks for maintaining this useful little library :)

**Comment by libwilliam** [comment]
My pleasure. I'm just happy people find it useful.
