### ISSUE TITLE
Does it work with jsonify? How to test?

### ISSUE THREAD

**Issue by blankclemens** [wichitacode/flask-compress#15]
Hello and thanks for this extension,

since it's so easy to use, I have no idea if it is actually working. My main question is if it works on jsonify responses, and if so, how to measure/test if and how good it compresses.

I tried to see my jsonify response in the browser and nothing changed, so I thought "maybe it's not working" - but on a second thought, maybe the browser is already decompressing so I don't see any change. Is there any way to see if it works?

Thanks a lot and best regards
Clemens

**Comment by blankclemens** [comment]
Using the DevTools from Chrome I could see that it works like a charm - 100KB jsonify response reduced to 16Kb! :)

**Comment by libwilliam** [comment]
Sorry for the delay getting back to you. Thank you for writing back with what you found out. I'm glad you are getting some value out of the extension!

**Comment by blankclemens** [comment]
"Some value" is a big underestimation - I had around 4-5MB per second to transfer, now it's only around 1MB which is way more practical. Thank you so much!
