### ISSUE TITLE
Please support Python 3?

### ISSUE THREAD

**Issue by brainix** [wichitacode/flask-compress#16]
Thank you for your amazing work.  Is there any way that we could get Python 3 support?

**Comment by libwilliam** [comment]
Thank you for the kind words!

It should work with [Python 3.3](https://travis-ci.org/wichitacode/flask-compress/jobs/58800902) and [Python 3.4](https://travis-ci.org/wichitacode/flask-compress/jobs/58800907). I've linked in the test results for both of those versions. 

Are you using an earlier version of the 3.x series? If so I can work on making it compatibility. Or are you having troubles with 3.3 or 3.4?

**Comment by brainix** [comment]
It may just be an issue of a missing Trove classifier?  I ran an automated testing tool to see which of my dependencies wouldn't work with Python 3 (https://caniusepython3.com/) and it flagged Flask-Compress.  Let me look into it a little more deeply and I'll get back to you with why.

Thank you for your quick response!  I'll respond with another (more intelligent) comment soon.

**Comment by libwilliam** [comment]
I dug into this and I think I now have it resolved. I wasn't manually specifying the Python versions that Flask-Compress supported in the `classifiers` section of `setup.py`. Now that I have set the specific values https://caniusepython3.com/project/Flask-Compress is validating correctly.

Thank you for bringing this to my attention!

**Comment by brainix** [comment]
Thank you!  :-)
